projetDotNet/projetDotNet/Models/cart.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetDotNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int CartID { get; set; }
        public int GameID { get; set; }
        public int clientID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantité { get; set; }
        public string GameName { get; set; }
        public Nullable<int> numeroCommande { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Game Game { get; set; }
    }
}

projetDotNet/projetDotNet/Controllers/InterfaceUserController.cs
using projetDotNet.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration.Conventions;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using System.Web.Mvc;

namespace projetDotNet.Controllers
{
    public class InterfaceUserController : Controller
    {
        private Database1Entities db = new Database1Entities();

        public ActionResult Index(string searchBy, string search, string sortBy)
        {
            ViewBag.SortNomParameter = String.IsNullOrEmpty(sortBy) ? "Nom desc" : "";
            ViewBag.SortGenreParameter = sortBy == "Genre" ? "Genre desc" : "Genre";

            var games = db.Game.AsQueryable();

            if (searchBy == "Genre")
            {
                games = games.Where(x => x.Genre == search || search == null);
            }
            else
            {
                games = games.Where(x => x.Nom.StartsWith(search) || search == null);
            }

            switch (sortBy)
            {
                case "Nom desc":
                    games = games.OrderByDescending(x => x.Nom);
                    break;
                case "Genre desc":
                    games = games.OrderByDescending(x => x.Genre);
                    break;
                case "Genre":
                    games = games.OrderBy(x => x.Genre);
                    break;
                default:
                    games = games.OrderBy(x => x.Nom);
                    break;
            }
            return View(games.ToList());
        }
        public ActionResult AddToCart(string id)
        {
            Session["id"] = id;
            return View();
        }
        [HttpPost]

        public ActionResult AddToCart(cart newcart)
        {   if (Request.IsAuthenticated)
            {
                var id = Convert.ToInt32(Session["id"]);
                newcart.GameID = id;
                newcart.date = DateTime.Now;
                newcart.CartID = db.cart.Count()+1;
                newcart.clientID = int.Parse(System.Web.HttpContext.Current.User.Identity.Name);
                var game = (from m in db.Game
                                  where m.Id == id
                                  select m).First();
                newcart.GameName = game.Nom;
                db.cart.Add(newcart);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            else return RedirectToAction("../Account/Login");

        }

        public ActionResult cart()
        {

            return View(db.cart.ToList());
        }

        public ActionResult Delete()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {

            var data = (from m in db.cart
                        where m.CartID == id
                        select m).First();

            if (data != null)
            {
                db.cart.Remove(data);
                db.SaveChanges();
                return RedirectToAction("cart");
            }
            else
                return View();

        }


        public ActionResult EditCart(int id)
        {
            var commandetoedit = (from m in db.cart
                              where m.CartID == id
                              select m).First();
            return View(commandetoedit);
        }

        [HttpPost]
        public ActionResult EditCart( cart commandetoedit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                var originalCommande = (from m in db.cart
                                    where m.CartID == commandetoedit.CartID
                                    select m).First();
                originalCommande.quantité = commandetoedit.quantité;
                
                db.SaveChanges();

                return RedirectToAction("cart");
            }
            catch
            {
                return View();
            }
        }



    }
}

projetDotNet/projetDotNet/Views/InterfaceUser/AddToCart.cshtml
@model projetDotNet.Models.cart

@{
    ViewBag.Title = "AddToCart";
}

<style>

    body {
        margin-top: 20px;
        background: #e2e2e5;
        background-image: url("https://png.pngtree.com/background/20210714/original/pngtree-carbon-fiber-abstract-background-with-red-lights-picture-image_1200965.jpg");
        background-repeat: repeat;
        background-position: top;
    }
</style>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal ">
            <h2 style=" text-align: center; font-family: 'Games' ,sans-serif; color:white"> Passer commande</h2>
            <hr />

            <div class="form-group" style="color:white;text-align:right" >
                @Html.LabelFor(model => model.quantité, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.quantité, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quantité, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group" style="color:white;text-align:left" >
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Créer" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div  style="text-align:center">
        @Html.ActionLink("Retour à l'écran d'acceuil", "Index")
    </div>
</body>

projetDotNet/projetDotNet/Views/InterfaceUser/Delete.cshtml
@model projetDotNet.Models.cart

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<div>
 

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "cart")
        </div>
    }
</div>

projetDotNet/projetDotNet/Views/InterfaceUser/EditCart.cshtml
@model projetDotNet.Models.cart

@{
    ViewBag.Title = "EditCart";
}

<h2>EditCart</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CartID)





        <div class="form-group">
            @Html.LabelFor(model => model.quantité, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantité, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantité, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "cart")
</div>

projetDotNet/projetDotNet/Views/InterfaceUser/Index.cshtml
@model IEnumerable<projetDotNet.Models.Game>


@{
    ViewBag.Title = "Index";

}
<!DOCTYPE html>
<html>
<head>

    <link href="https://fonts.cdnfonts.com/css/games" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style>

        body {
            margin-top: 20px;
            background: #e2e2e5;
            background-image: url("https://png.pngtree.com/background/20210714/original/pngtree-carbon-fiber-abstract-background-with-red-lights-picture-image_1200965.jpg");
            background-repeat: repeat;
            background-position: top;
        }
        
        .prod-info-main {
            border: 1px solid #ad3156;
            margin-bottom: 20px;
            margin-top: 10px;
            background: #fff;
            padding: 6px;
            -webkit-box-shadow: 0 1px 4px 0 rgba(21,180,255,0.5);
            box-shadow: 0 1px 1px 0 rgba(21,180,255,0.5);
        }

            .prod-info-main .product-image {
                background-color: #f2f2f2;
                display: block;
                min-height: 238px;
                overflow: hidden;
                position: relative;
                border: 1px solid #CEEFFF;
                padding-top: 40px;
            }

            .prod-info-main .product-deatil {
                border-bottom: 1px solid #dfe5e9;
                padding-bottom: 17px;
                padding-left: 16px;
                padding-top: 16px;
                position: relative;
                background: #fff
            }

        .product-content .product-deatil h5 a {
            color: #2f383d;
            font-size: 15px;
            line-height: 19px;
            text-decoration: none;
            padding-left: 0;
            margin-left: 0
        }

        .prod-info-main .product-deatil h5 a span {
            color: #9aa7af;
            display: block;
            font-size: 13px
        }

        .prod-info-main .product-deatil span.tag1 {
            border-radius: 50%;
            color: #fff;
            font-size: 15px;
            height: 50px;
            padding: 13px 0;
            position: absolute;
            right: 10px;
            text-align: center;
            top: 10px;
            width: 50px
        }

        .prod-info-main .product-deatil span.sale {
            background-color: #21c2f8
        }

        .prod-info-main .product-deatil span.discount {
            background-color: #71e134
        }

        .prod-info-main .product-deatil span.hot {
            background-color: #fa9442
        }

        .prod-info-main .description {
            font-size: 12.5px;
            line-height: 20px;
            padding: 10px 14px 16px 19px;
            background: #fff
        }

        .prod-info-main .product-info {
            padding: 11px 19px 10px 20px
        }

            .prod-info-main .product-info a.add-to-cart {
                color: #2f383d;
                font-size: 13px;
                padding-left: 16px
            }

        .prod-info-main name.a {
            padding: 5px 10px;
            margin-left: 16px
        }

        .product-info.smart-form .btn {
            padding: 6px 12px;
            margin-left: 12px;
            margin-top: -10px
        }

        .load-more-btn {
            background-color: #21c2f8;
            border-bottom: 2px solid #037ca5;
            border-radius: 2px;
            border-top: 2px solid #0cf;
            margin-top: 20px;
            padding: 9px 0;
            width: 100%
        }

        .product-block .product-deatil p.price-container span,
        .prod-info-main .product-deatil p.price-container span,
        .shipping table tbody tr td p.price-container span,
        .shopping-items table tbody tr td p.price-container span {
            color: #80243f;
            font-family: Lato, sans-serif;
            font-size: 24px;
            line-height: 20px
        }

        .product-info.smart-form .rating label {
            margin-top: 15px;
        }

        .prod-wrap .product-image span.tag2 {
            position: absolute;
            top: 10px;
            right: 10px;
            width: 36px;
            height: 36px;
            border-radius: 50%;
            padding: 10px 0;
            color: #fff;
            font-size: 11px;
            text-align: center
        }

        .prod-wrap .product-image span.tag3 {
            position: absolute;
            top: 10px;
            right: 20px;
            width: 60px;
            height: 36px;
            border-radius: 50%;
            padding: 10px 0;
            color: #fff;
            font-size: 11px;
            text-align: center
        }

        .prod-wrap .product-image span.sale {
            background-color: #57889c;
        }

        .prod-wrap .product-image span.hot {
            background-color: #a90329;
        }

        .prod-wrap .product-image span.special {
            background-color: #3B6764;
        }

        .shop-btn {
            position: relative
        }

            .shop-btn > span {
                background: #a90329;
                display: inline-block;
                font-size: 10px;
                box-shadow: inset 1px 1px 0 rgba(0, 0, 0, .1), inset 0 -1px 0 rgba(0, 0, 0, .07);
                font-weight: 700;
                border-radius: 50%;
                padding: 2px 4px 3px !important;
                text-align: center;
                line-height: normal;
                width: 19px;
                top: -7px;
                left: -7px
            }

        .product-deatil hr {
            padding: 0 0 5px !important
        }

        .product-deatil .glyphicon {
            color: #3276b1
        }

        .product-deatil .product-image {
            border-right: 0px solid #fff !important
        }

        .product-deatil .name {
            margin-top: 0;
            margin-bottom: 0
        }

            .product-deatil .name small {
                display: block
            }

            .product-deatil .name a {
                margin-left: 0
            }

        .product-deatil .price-container {
            font-size: 24px;
            margin: 0;
            font-weight: 300;
        }

            .product-deatil .price-container small {
                font-size: 12px;
            }

        .product-deatil .fa-2x {
            font-size: 16px !important
        }

            .product-deatil .fa-2x > h5 {
                font-size: 12px;
                margin: 0
            }

            .product-deatil .fa-2x + a,
            .product-deatil .fa-2x + a + a {
                font-size: 13px
            }

        .product-deatil .certified {
            margin-top: 10px
        }

            .product-deatil .certified ul {
                padding-left: 0
            }

                .product-deatil .certified ul li:not(first-child) {
                    margin-left: -3px
                }

                .product-deatil .certified ul li {
                    display: inline-block;
                    background-color: #f9f9f9;
                    padding: 13px 19px
                }

                    .product-deatil .certified ul li:first-child {
                        border-right: none
                    }

                    .product-deatil .certified ul li a {
                        text-align: left;
                        font-size: 12px;
                        color: #6d7a83;
                        line-height: 16px;
                        text-decoration: none
                    }

                        .product-deatil .certified ul li a span {
                            display: block;
                            color: #21c2f8;
                            font-size: 13px;
                            font-weight: 700;
                            text-align: center
                        }

        .product-deatil .message-text {
            width: calc(100% - 70px)
        }


        .prod-info-main div[class*=col-md-8] {
            padding: 0 13px 0 0
        }

        .prod-wrap div[class*=col-md-5] {
            padding-right: 0
        }

        .prod-wrap div[class*=col-md-7] {
            padding: 0 13px 0 0
        }

        .prod-info-main .product-image {
            border-right: 1px solid #dfe5e9
        }

        .prod-info-main .product-info {
            position: relative
        }
    </style>

</head>
<body>
    <br />
    <br />

    <h1 style="text-align: center;  font-family: 'Games',sans-serif; color:white">Bienvenu a GameStore,       
    votre meilleur magasin en ligne de jeu video. </h1>
    <br />
    <br />
    <p>
        <div style="text-align:center;">
            @using (@Html.BeginForm("Index", "InterfaceUser", FormMethod.Get))

            {
             <div >
                 <b style="color:white"> Chercher par :</b>
                 @Html.RadioButton("searchBy", "Nom", true)<text style="color:white">Nom</text>
                 @Html.RadioButton("searchBy", "Genre", true)<text style="color:white">Genre</text>
                 @Html.TextBox("search")

                 <input type="submit" value="Chercher" style="color:black" />
         
             </div>
            }
        </div>
    </p>
    <div class="container">
        @foreach (var item in Model)
        {
            <div class="col-xs-12 col-md-6">


                <div class="prod-info-main prod-wrap clearfix">

                    <div class="row">

                        <div class="col-md-5 col-sm-12 col-xs-12">

                            <div class="product-image">

                                <img src=@Html.DisplayFor(modelItem => item.ImageURL) class="img-responsive">

                                <span class="tag2 hot">

                                    SPECIAL

                                </span>

                            </div>

                        </div>

                        <div class="col-md-7 col-sm-12 col-xs-12">

                            <div class="product-deatil">

                                <h5 class="name">

                                    <a href="#">

                                        @Html.DisplayFor(modelItem => item.Nom)

                                    </a>

                                    <a href="#">

                                        <span>
                                            @Html.DisplayFor(modelItem => item.Genre)
                                        </span>

                                    </a>

                                </h5>

                                <p class="price-container">

                                    <span>
                                        @Html.DisplayFor(modelItem => item.Price)
                                    </span>

                                </p>

                                <span class="tag1"></span>

                            </div>

                            <div class="description">

                                <p>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </p>

                            </div>

                            <div class="product-info smart-form">

                                <div class="row">

                                    <div class="col-md-12"  style="color:white">>


                                        <div class="btn btn-danger">
                                            @Html.ActionLink("Add to cart", "AddToCart", new { id = item.Id.ToString() })
                                        </div>

                                        <a href="javascript:void(0);" class="btn btn-info">More info</a>

                                    </div>

                                    <div class="col-md-12">

                                        <div class="rating">
                                            Rating:

                                            <label for="stars-rating-5"><i class="fa fa-star text-danger"></i></label>

                                            <label for="stars-rating-4"><i class="fa fa-star text-danger"></i></label>

                                            <label for="stars-rating-3"><i class="fa fa-star text-danger"></i></label>

                                            <label for="stars-rating-2"><i class="fa fa-star text-warning"></i></label>

                                            <label for="stars-rating-1"><i class="fa fa-star text-warning"></i></label>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>
                </div>


            </div>
        }
    </div>

</body>
</html>

projetDotNet/projetDotNet/Views/InterfaceUser/cart.cshtml
@model IEnumerable<projetDotNet.Models.cart>

@{
    ViewBag.Title = "cart";
}
<!DOCTYPE html>
<head>
    <link href="https://fonts.cdnfonts.com/css/games" rel="stylesheet">
</head>


<style>

    body {
        margin-top: 20px;
        background: #e2e2e5;
        background-image: url("https://png.pngtree.com/background/20210714/original/pngtree-carbon-fiber-abstract-background-with-red-lights-picture-image_1200965.jpg");
        background-repeat: repeat;
        background-position: top;
    }
</style>

<body>
    <h2 style=" text-align: center; font-family: 'Games' ,sans-serif; color:white"> Cart</h2>

    <table class="table">
        <tr>
            <th> Game </th>
            <th>
                Quantité
            </th>

            <th> Date</th>
            <th> </th>
        </tr>
        @foreach (var item in Model)
        {
            if (item.clientID == int.Parse(System.Web.HttpContext.Current.User.Identity.Name))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.GameName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantité)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.date)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "EditCart", new { id = item.CartID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.CartID })
                    </td>
                </tr>
            }
        }
    </table>

    <p>
        @Html.ActionLink("valider", "valider") |
        @Html.ActionLink("Back to shop", "index")
    </p>
</body>

projetDotNet/projetDotNet/Views/InterfaceUser/valider.cshtml
@{
    ViewBag.Title = "valider";
}

<h4>commande validée !</h4>
<h4>merci pour votre visite.</h4>


@Html.ActionLink("Back to shop", "index") 