projetDotNet/projetDotNet/Controllers/AdminInterfaceController.cs
using projetDotNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace projetDotNet.Controllers
{
    public class AdminInterfaceController : Controller
    {
        private Database1Entities db = new Database1Entities();
        // GET: AdminInterface
        public ActionResult Index(string searchBy, string search, string sortBy)
        {
            ViewBag.SortNomParameter = String.IsNullOrEmpty(sortBy) ? "Nom desc" : "";
            ViewBag.SortGenreParameter = sortBy == "Genre" ? "Genre desc" : "Genre";

            var games = db.Game.AsQueryable();

            if (searchBy == "Genre")
            {
                games = games.Where(x => x.Genre == search || search == null);
            }
            else
            {
                games = games.Where(x => x.Nom.StartsWith(search) || search == null);
            }

            switch (sortBy)
            {
                case "Nom desc":
                    games = games.OrderByDescending(x => x.Nom);
                    break;
                case "Genre desc":
                    games = games.OrderByDescending(x => x.Genre);
                    break;
                case "Genre":
                    games = games.OrderBy(x => x.Genre);
                    break;
                default:
                    games = games.OrderBy(x => x.Nom);
                    break;
            }
            return View(games.ToList());
        }
            public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Id")] Game gameToCreate)
        {
                db.Game.Add(gameToCreate);
                db.SaveChanges();
               return RedirectToAction("Index");

        }
        public ActionResult Edit(int id)
        {
            var gameToEdit = (from m in db.Game
                              where m.Id == id
                              select m).First();
            return View(gameToEdit);
        }

        [HttpPost]
        public ActionResult Edit(int id, Game gameToEdit)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                var originalGame = (from m in db.Game
                                    where m.Id == gameToEdit.Id
                                    select m).First();
                originalGame.Nom = gameToEdit.Nom;
                originalGame.Date_de_sortie = gameToEdit.Date_de_sortie;
                originalGame.Genre = gameToEdit.Genre;
                originalGame.Description = gameToEdit.Description;
                originalGame.ImageURL = gameToEdit.ImageURL;
                originalGame.Price = gameToEdit.Price;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: Home/Delete/5
        public ActionResult Delete()
        {
            return View();
        }


        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {

            var data = (from m in db.Game
                        where m.Id == id
                        select m).First();

            if (data != null)
            {
                db.Game.Remove(data);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
                return View();

        }
        public ActionResult Details(int id)
        {
            var gameToEdit = (from m in db.Game
                              where m.Id == id
                              select m).First();
            return View(gameToEdit);
        }

    }
}

projetDotNet/projetDotNet/Views/AdminInterface/Create.cshtml
@model projetDotNet.Models.Game

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_de_sortie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_de_sortie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_de_sortie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

projetDotNet/projetDotNet/Views/AdminInterface/Delete.cshtml
@model projetDotNet.Models.Game

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this game ?</h3>
<div>
    

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

projetDotNet/projetDotNet/Views/AdminInterface/Details.cshtml
@model projetDotNet.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Editeur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editeur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_de_sortie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_de_sortie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

projetDotNet/projetDotNet/Views/AdminInterface/Edit.cshtml
@model projetDotNet.Models.Game

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_de_sortie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_de_sortie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_de_sortie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

projetDotNet/projetDotNet/Views/AdminInterface/Index.cshtml
@model IEnumerable<projetDotNet.Models.Game>

@{
    ViewBag.Title = "Index";
}
<h3>@ViewBag.Message</h3>
<h2 style="text-align:center">La liste des jeux disponibles dans notre stock</h2>
<br />

<p>
    <div  style="text-align:center"> 
        @using (@Html.BeginForm("Index", "AdminInterface", FormMethod.Get))

        {<b> Chercher par :</b>

            @Html.RadioButton("searchBy", "Nom", true)<text>Nom</text>
            @Html.RadioButton("searchBy", "Genre", true)<text>Genre</text>
            @Html.TextBox("search")
            <input type="submit" value="Search" />
        }
    </div>
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.ActionLink("Nom", "Index", new { sortBy = ViewBag.SortNomParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editeur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_de_sortie)
        </th>
        <th>
            @Html.ActionLink("Genre", "Index", new { sortBy = ViewBag.SortGenreParameter, searchBy = Request.QueryString["searchBy"], search = Request["search"] })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img class="rounded-circle" src="@item.ImageURL" alt="@item.Nom" style="max-width: 150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editeur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_de_sortie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>